defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

action: "info"
model: ""

maze:
  height:
    min: 5
    max: 5
  width:
    min: 5
    max: 5
  test_percent: 0.1
  number_per_dimension: 200000

output:
  dir: out
  model: out/models
  data: out/data
  tokenizer: out/tokenizer.json

tokenizer:
  vocab_size: 1000
  fragment_length: 1000
  min_frequency: 10000
  batch_size: 10000
  pad_token: "[PAD]"
  mask_token: "[MASK]"

training:
  output_dir: out/models
  logging_steps: 10
  save_total_limit: 3
  optim: adamw_torch
#  logging_strategy: steps

sample:
  width: 5
  height: 5