defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

action: "info"
model: ""

maze:
  height:
    min: 3
    max: 3
  width:
    min: 3
    max: 3
  test_percent: 0.1
  number_per_dimension: 100000

output:
  dir: out
  model: out/models
  data: out/data
  tokenizer: out/tokenizer.json

tokenizer:
  vocab_size: 1000
  fragment_length: 1000
  min_frequency: 100000
  batch_size: 10000

training:
  output_dir: out/model
  evaluation_strategy: steps
  overwrite_output_dir: True
  num_train_epochs: 10
  save_steps: 10
  logging_steps: 10
  logging_strategy: steps
  gradient_accumulation_steps: 32
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 16
  save_total_limit: 3
  optim: adamw_torch